
service: retoRimac

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    SWAPI_BASE_URL: https://swapi.py4e.com/api 


functions:
  loadData:
    handler: handler.loadData
    events:
      - http:
          method: post
          path: cargarDatosSWAPI
